# Generated by Django 5.1.5 on 2025-01-27 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be exactly 10 digits, starting with '9'.", regex='^(9[3-9]\\d{8})$')]),
        ),
    ]
